off:
  pitch:
    p: 0
    d: 0
  roll:
    p: 0
    d: 0
  yaw:
    p: 0
    d: 0
weak:
  pitch:
    p: 1000
    d: 0
  roll:
    p: 1000
    d: 0
  yaw:
    p: 0
    d: 0
medium:
  pitch:
    p: 3000
    d: 0
  roll:
    p: 3000
    d: 0
  yaw:
    p: 0
    d: 0
default:
  pitch:
    p: 220
    d: 70000
  roll:
    p: 250
    d: 70000
  yaw:
    p: 1500
    d: 70000